version: '3'
services:
  redis_db:
    container_name: redis_db
    image: redis:latest
    hostname: redis
    cap_add:
      - IPC_LOCK
      - SYS_PTRACE
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: on-failure:3
    labels:
      - service_name=redis
      - image_name=redis:latest
      - service_type=redis
  go-user-admin:
    depends_on:
      - redis_db
    container_name: go-user-admin-redis
    image: megaease/go-apm-use-admin-redis-example:1.0.0
    environment:
      REDIS_HOST_AND_PORT: "redis_db:6379"
    ports:
      - "8090"


