version: "2"

services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    cap_add:
      - IPC_LOCK
      - SYS_PTRACE
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: on-failure:3
    ports:
     - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"
    labels:
      - service_name=redis
      - image_name=redis:latest
      - service_type=redis
