version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.27
    hostname: mysql
    restart: on-failure:2

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=megaease
      - MYSQL_PASSWORD=8a4b041e
      - MYSQL_DATABASE=easeservicemonitor

    volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/db.sql

    logging:
      driver: json-file
      options:
        max-size: 100m

networks:
  easeload:
    external: true
