version: '3'
services:
  php-user-frontend:
    container_name: php-user-frontend
    image: megaease/php-apm-frontend-example:1.0.0
    environment:
      USER_LIST_URL: "http://192.168.0.111:18888/user/list"
      CHECK_ROOT_URL: "http://192.168.0.111:8090/is_root"
    ports:
      - "8081:8081"
