version: '3'
services:
  net-manager-service:
    container_name: net-manager
    image: megaease/net-apm-manager-example:1.0.0
    environment:
      USER_ENDPOINT: "http://docker.for.mac.localhost:18888/user"
    ports:
      - "7116:7116"
